// Auto-generated by OpenLane
module aes_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset_n,
  input encdec,
  input init,
  input next,
  output ready,
  input[255:0] key,
  input keylen,
  input[127:0] block,
  output[127:0] result,
  output result_valid
);
endmodule
